/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemadmin;

/**
 *
 * @author nikhilbindal
 */
public class SysAdminHome extends javax.swing.JFrame {

    /**
     * Creates new form SysAdminHome
     */
    public SysAdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        lblUserImg = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        btnViewLoggedInUserProfile = new javax.swing.JPanel();
        lblViewUserProfile = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JPanel();
        lblDashIcon = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JPanel();
        lblEmpIcon = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        btnViewLogout = new javax.swing.JPanel();
        lblLogoutBtn = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        lblCloseWindowIcon = new javax.swing.JLabel();
        lblAboutUS = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        lblEmpSec = new javax.swing.JLabel();
        lblEmpInfoIcon = new javax.swing.JLabel();
        addEmployeePanel = new javax.swing.JPanel();
        lblIconAddEmployee = new javax.swing.JLabel();
        lblAddEmployee = new javax.swing.JLabel();
        updateEmployeePanel = new javax.swing.JPanel();
        lblIconUpdateEmployee = new javax.swing.JLabel();
        lblUpdateEmployee = new javax.swing.JLabel();
        deleteEmployeePanel = new javax.swing.JPanel();
        lblIconDeleteEmployee = new javax.swing.JLabel();
        lblDeleteEmployee = new javax.swing.JLabel();
        updateEmployeePanel1 = new javax.swing.JPanel();
        lblIconUpdateEmployee1 = new javax.swing.JLabel();
        lblUpdateEmployee1 = new javax.swing.JLabel();
        deleteEmployeePanel1 = new javax.swing.JPanel();
        lblIconDeleteEmployee1 = new javax.swing.JLabel();
        lblDeleteEmployee2 = new javax.swing.JLabel();
        lblEmpSec1 = new javax.swing.JLabel();
        addEmployeePanel1 = new javax.swing.JPanel();
        lblIconAddEmployee1 = new javax.swing.JLabel();
        lblAddEmployee1 = new javax.swing.JLabel();
        addEmployeePanel2 = new javax.swing.JPanel();
        lblIconAddEmployee2 = new javax.swing.JLabel();
        lblAddEmployee2 = new javax.swing.JLabel();
        updateEmployeePanel2 = new javax.swing.JPanel();
        lblIconUpdateEmployee2 = new javax.swing.JLabel();
        lblUpdateEmployee2 = new javax.swing.JLabel();
        deleteEmployeePanel2 = new javax.swing.JPanel();
        lblIconDeleteEmployee2 = new javax.swing.JLabel();
        lblDeleteEmployee3 = new javax.swing.JLabel();
        lblEmpSec2 = new javax.swing.JLabel();
        addEmployeePane = new javax.swing.JPanel();
        addEmpPaneHeader = new javax.swing.JPanel();
        lblAddEmployeePane = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblDesg = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblEmpId = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        r_Active = new javax.swing.JRadioButton();
        r_InActive = new javax.swing.JRadioButton();
        lblStatus = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        r_otherGender = new javax.swing.JRadioButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblEmployeePic = new javax.swing.JLabel();
        empStartDateField = new com.toedter.calendar.JDateChooser();
        btnAdd2 = new javax.swing.JButton();
        panelEmployees = new javax.swing.JPanel();
        panelEmployeeHeader = new javax.swing.JPanel();
        TotalEmpPane = new javax.swing.JPanel();
        lblTotalEmp = new javax.swing.JLabel();
        txtTotalEmp = new javax.swing.JLabel();
        activeEmpPane = new javax.swing.JPanel();
        txtActiveEmp = new javax.swing.JLabel();
        lblActiveEmp = new javax.swing.JLabel();
        lblInActiveEmp = new javax.swing.JLabel();
        txtInactiveEmp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeesData = new javax.swing.JTable();
        txtSearch1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(153, 153, 153)));
        dashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 0, 104));
        sidePanel.setPreferredSize(new java.awt.Dimension(130, 600));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User_Icon.png"))); // NOI18N
        sidePanel.add(lblUserImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 80));

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 204, 0));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Admin");
        sidePanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 15));

        lblDesignation.setBackground(new java.awt.Color(255, 255, 255));
        lblDesignation.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        lblDesignation.setForeground(new java.awt.Color(102, 204, 255));
        lblDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesignation.setText("System Admin");
        sidePanel.add(lblDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, -1));

        btnViewLoggedInUserProfile.setBackground(new java.awt.Color(0, 0, 51));

        lblViewUserProfile.setBackground(new java.awt.Color(240, 240, 240));
        lblViewUserProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblViewUserProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblViewUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewUserProfile.setText("View Profile");
        lblViewUserProfile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout btnViewLoggedInUserProfileLayout = new javax.swing.GroupLayout(btnViewLoggedInUserProfile);
        btnViewLoggedInUserProfile.setLayout(btnViewLoggedInUserProfileLayout);
        btnViewLoggedInUserProfileLayout.setHorizontalGroup(
            btnViewLoggedInUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnViewLoggedInUserProfileLayout.setVerticalGroup(
            btnViewLoggedInUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        sidePanel.add(btnViewLoggedInUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 51));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        btnDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Laptop_Icon.png"))); // NOI18N
        btnDashboard.add(lblDashIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 130, 30));

        lblDashboard.setBackground(new java.awt.Color(240, 240, 240));
        lblDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Dashboard");
        btnDashboard.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 10));

        sidePanel.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 160, 124, 60));

        btnEmployee.setBackground(new java.awt.Color(0, 0, 51));
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseClicked(evt);
            }
        });
        btnEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Leave_Icon.png"))); // NOI18N
        btnEmployee.add(lblEmpIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 130, 30));

        lblEmployee.setBackground(new java.awt.Color(240, 240, 240));
        lblEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployee.setText("Reports");
        btnEmployee.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 20));

        sidePanel.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 220, 124, 60));

        btnViewLogout.setBackground(new java.awt.Color(0, 0, 51));
        btnViewLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewLogoutMouseClicked(evt);
            }
        });

        lblLogoutBtn.setBackground(new java.awt.Color(240, 240, 240));
        lblLogoutBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblLogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoutBtn.setText("Log Out");
        lblLogoutBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout btnViewLogoutLayout = new javax.swing.GroupLayout(btnViewLogout);
        btnViewLogout.setLayout(btnViewLogoutLayout);
        btnViewLogoutLayout.setHorizontalGroup(
            btnViewLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        btnViewLogoutLayout.setVerticalGroup(
            btnViewLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        sidePanel.add(btnViewLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 500, 124, 30));

        dashboardPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 2, new java.awt.Color(153, 153, 153)));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCloseWindowIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseWindowIconMouseClicked(evt);
            }
        });
        headerPanel.add(lblCloseWindowIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 5, -1, -1));

        lblAboutUS.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAboutUS.setForeground(new java.awt.Color(153, 153, 153));
        lblAboutUS.setText("About Us");
        lblAboutUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAboutUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutUSMouseClicked(evt);
            }
        });
        headerPanel.add(lblAboutUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 5, 70, 24));

        lblContact.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblContact.setForeground(new java.awt.Color(153, 153, 153));
        lblContact.setText("Contact");
        lblContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactMouseClicked(evt);
            }
        });
        headerPanel.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, 60, 24));

        dashboardPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 900, 35));

        controlPanel.setLayout(new java.awt.CardLayout());

        panelDashboard.setBackground(new java.awt.Color(218, 228, 230));

        lblEmpSec.setBackground(new java.awt.Color(240, 240, 240));
        lblEmpSec.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmpSec.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpSec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpSec.setText("Hospitals Section");

        lblEmpInfoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        addEmployeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeePanelMouseClicked(evt);
            }
        });
        addEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconAddEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add_Icon.png"))); // NOI18N
        addEmployeePanel.add(lblIconAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblAddEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAddEmployee.setForeground(new java.awt.Color(51, 204, 0));
        lblAddEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddEmployee.setText("Create Hospital");
        addEmployeePanel.add(lblAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        updateEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        updateEmployeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateEmployeePanelMouseClicked(evt);
            }
        });
        updateEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconUpdateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUpdateEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Update_Icon.png"))); // NOI18N
        updateEmployeePanel.add(lblIconUpdateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblUpdateEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUpdateEmployee.setForeground(new java.awt.Color(0, 102, 204));
        lblUpdateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateEmployee.setText("Update Hospital");
        updateEmployeePanel.add(lblUpdateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        deleteEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        deleteEmployeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeePanelMouseClicked(evt);
            }
        });
        deleteEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconDeleteEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete_Icon.png"))); // NOI18N
        deleteEmployeePanel.add(lblIconDeleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblDeleteEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDeleteEmployee.setForeground(new java.awt.Color(204, 0, 0));
        lblDeleteEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteEmployee.setText("Delete Hospital");
        deleteEmployeePanel.add(lblDeleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        updateEmployeePanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        updateEmployeePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateEmployeePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateEmployeePanel1MouseClicked(evt);
            }
        });
        updateEmployeePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconUpdateEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUpdateEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Update_Icon.png"))); // NOI18N
        updateEmployeePanel1.add(lblIconUpdateEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblUpdateEmployee1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUpdateEmployee1.setForeground(new java.awt.Color(0, 102, 204));
        lblUpdateEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateEmployee1.setText("Update Vendor");
        updateEmployeePanel1.add(lblUpdateEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        deleteEmployeePanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        deleteEmployeePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteEmployeePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeePanel1MouseClicked(evt);
            }
        });
        deleteEmployeePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconDeleteEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDeleteEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete_Icon.png"))); // NOI18N
        deleteEmployeePanel1.add(lblIconDeleteEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblDeleteEmployee2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDeleteEmployee2.setForeground(new java.awt.Color(204, 0, 0));
        lblDeleteEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteEmployee2.setText("Delete Vendor");
        deleteEmployeePanel1.add(lblDeleteEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        lblEmpSec1.setBackground(new java.awt.Color(240, 240, 240));
        lblEmpSec1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmpSec1.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpSec1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpSec1.setText("Vendors Section");

        addEmployeePanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        addEmployeePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeePanel1MouseClicked(evt);
            }
        });
        addEmployeePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconAddEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAddEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add_Icon.png"))); // NOI18N
        addEmployeePanel1.add(lblIconAddEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblAddEmployee1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAddEmployee1.setForeground(new java.awt.Color(51, 204, 0));
        lblAddEmployee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddEmployee1.setText("Create Vendor");
        addEmployeePanel1.add(lblAddEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        addEmployeePanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        addEmployeePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeePanel2MouseClicked(evt);
            }
        });
        addEmployeePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconAddEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconAddEmployee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add_Icon.png"))); // NOI18N
        addEmployeePanel2.add(lblIconAddEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblAddEmployee2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAddEmployee2.setForeground(new java.awt.Color(51, 204, 0));
        lblAddEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddEmployee2.setText("Create NGO");
        addEmployeePanel2.add(lblAddEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        updateEmployeePanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        updateEmployeePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateEmployeePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateEmployeePanel2MouseClicked(evt);
            }
        });
        updateEmployeePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconUpdateEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUpdateEmployee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Update_Icon.png"))); // NOI18N
        updateEmployeePanel2.add(lblIconUpdateEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblUpdateEmployee2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUpdateEmployee2.setForeground(new java.awt.Color(0, 102, 204));
        lblUpdateEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateEmployee2.setText("Update NGO");
        updateEmployeePanel2.add(lblUpdateEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        deleteEmployeePanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        deleteEmployeePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteEmployeePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeePanel2MouseClicked(evt);
            }
        });
        deleteEmployeePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconDeleteEmployee2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDeleteEmployee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete_Icon.png"))); // NOI18N
        deleteEmployeePanel2.add(lblIconDeleteEmployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        lblDeleteEmployee3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDeleteEmployee3.setForeground(new java.awt.Color(204, 0, 0));
        lblDeleteEmployee3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteEmployee3.setText("Delete NGO");
        deleteEmployeePanel2.add(lblDeleteEmployee3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 160, 30));

        lblEmpSec2.setBackground(new java.awt.Color(240, 240, 240));
        lblEmpSec2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmpSec2.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpSec2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpSec2.setText("NGOs Section");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDashboardLayout.createSequentialGroup()
                                .addComponent(addEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDashboardLayout.createSequentialGroup()
                                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmpInfoIcon))
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addComponent(addEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEmpSec2)
                    .addComponent(lblEmpSec1)
                    .addComponent(lblEmpSec))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblEmpInfoIcon))
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblEmpSec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lblEmpSec1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteEmployeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(lblEmpSec2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEmployeePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        controlPanel.add(panelDashboard, "card2");

        addEmployeePane.setBackground(new java.awt.Color(218, 228, 230));
        addEmployeePane.setPreferredSize(new java.awt.Dimension(769, 560));

        addEmpPaneHeader.setBackground(new java.awt.Color(0, 0, 102));
        addEmpPaneHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addEmpPaneHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEmployeePane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddEmployeePane.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmployeePane.setText("Add Employee :");
        addEmpPaneHeader.add(lblAddEmployeePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Go Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        addEmpPaneHeader.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 4, 110, 30));

        lblFName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFName.setForeground(new java.awt.Color(153, 153, 153));
        lblFName.setText("First Name :");

        txtFname.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtFname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName.setForeground(new java.awt.Color(153, 153, 153));
        lblLName.setText("Last Name :");

        txtLname.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtLname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDepartment.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(153, 153, 153));
        lblDepartment.setText("Department :");

        txtDepartment.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtDepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDesg.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDesg.setForeground(new java.awt.Color(153, 153, 153));
        lblDesg.setText("Designation :");

        txtDesignation.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtDesignation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblContactNo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(153, 153, 153));
        lblContactNo.setText("Contact No :");

        txtNumber.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress.setText("Address :");

        txtAddress.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblEmpId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmpId.setForeground(new java.awt.Color(153, 153, 153));
        lblEmpId.setText("Employee ID :");

        txtEmpId.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtEmpId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        btnAdd.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Employee");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        r_Active.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        r_Active.setText("Active");
        r_Active.setContentAreaFilled(false);
        r_Active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_ActiveActionPerformed(evt);
            }
        });

        r_InActive.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        r_InActive.setText("In - Active");
        r_InActive.setContentAreaFilled(false);
        r_InActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_InActiveActionPerformed(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(153, 153, 153));
        lblStatus.setText("Status :");

        lblStartDate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblStartDate.setForeground(new java.awt.Color(153, 153, 153));
        lblStartDate.setText("Start Date :");

        lblGender.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(153, 153, 153));
        lblGender.setText("Gender");

        r_male.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        r_male.setText("Male");
        r_male.setContentAreaFilled(false);
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        r_female.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        r_female.setText("Female");
        r_female.setContentAreaFilled(false);
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        r_otherGender.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        r_otherGender.setText("Other");
        r_otherGender.setContentAreaFilled(false);
        r_otherGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_otherGenderActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(153, 153, 153));
        lblEmail.setText("Email :");

        txtEmail.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtAge.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAge.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(153, 153, 153));
        lblAge.setText("Age :");

        lblEmployeePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAdd2.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd2.setText("Upload Photo");
        btnAdd2.setBorderPainted(false);
        btnAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addEmployeePaneLayout = new javax.swing.GroupLayout(addEmployeePane);
        addEmployeePane.setLayout(addEmployeePaneLayout);
        addEmployeePaneLayout.setHorizontalGroup(
            addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(69, 684, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmpId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(lblDepartment, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblContactNo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addComponent(lblEmpId)
                            .addComponent(lblGender)
                            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(r_male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r_female)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r_otherGender)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStartDate)
                            .addComponent(lblStatus)
                            .addComponent(lblDesg)
                            .addComponent(lblLName)
                            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(r_Active)
                                .addGap(18, 18, 18)
                                .addComponent(r_InActive))
                            .addComponent(txtDesignation)
                            .addComponent(txtLname, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(empStartDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(lblEmployeePic, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(btnAdd2)
                                .addGap(59, 59, 59))))))
        );
        addEmployeePaneLayout.setVerticalGroup(
            addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                .addComponent(addEmpPaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpId)
                    .addComponent(lblStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmpId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(empStartDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(lblFName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addEmployeePaneLayout.createSequentialGroup()
                                .addComponent(lblLName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDepartment)
                            .addComponent(lblDesg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactNo)
                            .addComponent(lblStatus)))
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(lblEmployeePic, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_Active)
                    .addComponent(r_InActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_male)
                            .addComponent(r_female)
                            .addComponent(r_otherGender)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAge))
                .addGap(9, 9, 9)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePaneLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        controlPanel.add(addEmployeePane, "card7");

        panelEmployees.setBackground(new java.awt.Color(218, 228, 230));

        panelEmployeeHeader.setBackground(new java.awt.Color(0, 0, 102));
        panelEmployeeHeader.setPreferredSize(new java.awt.Dimension(769, 110));

        TotalEmpPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TotalEmpPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TotalEmpPane.setPreferredSize(new java.awt.Dimension(170, 120));
        TotalEmpPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalEmp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalEmp.setForeground(new java.awt.Color(0, 0, 102));
        lblTotalEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalEmp.setText("Total Employees");
        lblTotalEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TotalEmpPane.add(lblTotalEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        txtTotalEmp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTotalEmp.setForeground(new java.awt.Color(0, 0, 104));
        txtTotalEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalEmp.setText("0.00");
        txtTotalEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TotalEmpPane.add(txtTotalEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 50));

        activeEmpPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        activeEmpPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activeEmpPane.setPreferredSize(new java.awt.Dimension(170, 120));
        activeEmpPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtActiveEmp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtActiveEmp.setForeground(new java.awt.Color(0, 0, 104));
        txtActiveEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActiveEmp.setText("0.00");
        txtActiveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activeEmpPane.add(txtActiveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 50));

        lblActiveEmp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActiveEmp.setForeground(new java.awt.Color(0, 0, 102));
        lblActiveEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActiveEmp.setText("Active");
        lblActiveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activeEmpPane.add(lblActiveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, -1));

        lblInActiveEmp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInActiveEmp.setForeground(new java.awt.Color(0, 0, 102));
        lblInActiveEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInActiveEmp.setText("In - Active");
        lblInActiveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activeEmpPane.add(lblInActiveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, -1));

        txtInactiveEmp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtInactiveEmp.setForeground(new java.awt.Color(0, 0, 104));
        txtInactiveEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInactiveEmp.setText("0.00");
        txtInactiveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activeEmpPane.add(txtInactiveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, 50));

        javax.swing.GroupLayout panelEmployeeHeaderLayout = new javax.swing.GroupLayout(panelEmployeeHeader);
        panelEmployeeHeader.setLayout(panelEmployeeHeaderLayout);
        panelEmployeeHeaderLayout.setHorizontalGroup(
            panelEmployeeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(activeEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmployeeHeaderLayout.setVerticalGroup(
            panelEmployeeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEmployeeHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jScrollPane1.setBackground(new java.awt.Color(32, 136, 203));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(218, 228, 230)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblEmployeesData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblEmployeesData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Designation", "Department", "Contact No", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployeesData.setFocusable(false);
        tblEmployeesData.setGridColor(new java.awt.Color(204, 204, 204));
        tblEmployeesData.setPreferredSize(new java.awt.Dimension(450, 618));
        tblEmployeesData.setRowHeight(25);
        tblEmployeesData.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblEmployeesData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmployeesData);

        txtSearch1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtSearch1.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch1.setText("                                                           Enter Employee Id, First Name or Email to Search");
        txtSearch1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtSearch1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearch1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearch1FocusLost(evt);
            }
        });
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        txtSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearch1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelEmployeesLayout = new javax.swing.GroupLayout(panelEmployees);
        panelEmployees.setLayout(panelEmployeesLayout);
        panelEmployeesLayout.setHorizontalGroup(
            panelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEmployeeHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(panelEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEmployeesLayout.setVerticalGroup(
            panelEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeesLayout.createSequentialGroup()
                .addComponent(panelEmployeeHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        controlPanel.add(panelEmployees, "card3");

        dashboardPanel.add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 35, 770, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        addEmployeePane.setVisible(false);
        panelDashboard.setVisible(true);
        panelEmployees.setVisible(false);
        updateEmployeePane.setVisible(false);
        deleteEmployeePane.setVisible(false);
        reportEmployeePane.setVisible(false);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseClicked
        // TODO add your handling code here:
        txtTotalEmp.setText(String.valueOf(this.employees.getTotalEmployeesCount()));
        txtActiveEmp.setText(String.valueOf(this.employees.getActiveEmployeesCount()));
        txtInactiveEmp.setText(String.valueOf(this.employees.getInActiveEmployeesCount()));
        addEmployeePane.setVisible(false);
        panelDashboard.setVisible(false);
        panelEmployees.setVisible(true);
        updateEmployeePane.setVisible(false);
        deleteEmployeePane.setVisible(false);
        reportEmployeePane.setVisible(false);

        populateEmployeesDataToTable(null);
    }//GEN-LAST:event_btnEmployeeMouseClicked

    private void btnViewLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewLogoutMouseClicked
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewLogoutMouseClicked

    private void lblCloseWindowIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseWindowIconMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblCloseWindowIconMouseClicked

    private void lblAboutUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutUSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAboutUSMouseClicked

    private void lblContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContactMouseClicked

    private void addEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeePanelMouseClicked
        // TODO add your handling code here:
        addEmployeePane.setVisible(true);
        panelDashboard.setVisible(false);
        panelEmployees.setVisible(false);
        updateEmployeePane.setVisible(false);
        deleteEmployeePane.setVisible(false);
        reportEmployeePane.setVisible(false);
    }//GEN-LAST:event_addEmployeePanelMouseClicked

    private void updateEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeePanelMouseClicked
        // TODO add your handling code here:
        addEmployeePane.setVisible(false);
        panelDashboard.setVisible(false);
        panelEmployees.setVisible(false);
        updateEmployeePane.setVisible(true);
        deleteEmployeePane.setVisible(false);
        reportEmployeePane.setVisible(false);
    }//GEN-LAST:event_updateEmployeePanelMouseClicked

    private void deleteEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeePanelMouseClicked
        // TODO add your handling code here:
        addEmployeePane.setVisible(false);
        panelDashboard.setVisible(false);
        panelEmployees.setVisible(false);
        updateEmployeePane.setVisible(false);
        deleteEmployeePane.setVisible(true);
        reportEmployeePane.setVisible(false);
    }//GEN-LAST:event_deleteEmployeePanelMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        addEmployeePane.setVisible(false);
        panelDashboard.setVisible(true);
        panelEmployees.setVisible(false);
        updateEmployeePane.setVisible(false);
        deleteEmployeePane.setVisible(false);
        reportEmployeePane.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(!ValidationForCreateEmployee()) {
            return;
        }
        String fname = txtFname.getText();
        String lname = txtLname.getText();
        int age =  txtAge.getText().isEmpty() ? null : Integer.parseInt(txtAge.getText());
        boolean status = this.empStatus;
        String gender = this.empGender;
        JDateChooser startDate = empStartDateField;
        String dept = txtDepartment.getText();
        String designation = txtDesignation.getText();
        int empID =  txtEmpId.getText().isEmpty() ? null : Integer.parseInt(txtEmpId.getText());
        String profilePic = "";
        String email = txtEmail.getText();
        String phnNo = txtNumber.getText();
        String address = txtAddress.getText();
        ContactDetails contactDetail = new ContactDetails(phnNo, email, address);

        Employee employee = employees.addNewEmployees();
        employee.setAge(age);
        employee.setContactDetails(contactDetail);
        employee.setDept(dept);
        employee.setDesignation(designation);
        employee.setEmpID(empID);
        employee.setStatus(status);
        employee.setStartDate(startDate);
        employee.setProfilePic(profilePic);
        employee.setFname(fname);
        employee.setLname(lname);
        employee.setGender(gender);
        employee.setProfilePic(this.imagePath);

        JOptionPane.showMessageDialog(this, "Employee Details Added!");

        txtEmpId.setText("");
        txtFname.setText("");
        txtLname.setText("");
        txtAge.setText("");
        txtNumber.setText("");
        txtEmail.setText("");
        txtAddress.setText("");
        r_Active.setSelected(false);
        r_InActive.setSelected(false);
        r_male.setSelected(false);
        r_female.setSelected(false);
        r_otherGender.setSelected(false);
        txtDepartment.setText("");
        txtDesignation.setText("");
        empStartDateField.setDate(new Date());

    }//GEN-LAST:event_btnAddActionPerformed

    private void r_ActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_ActiveActionPerformed
        // TODO add your handling code here:
        this.empStatus = true;
        r_InActive.setSelected(false);
    }//GEN-LAST:event_r_ActiveActionPerformed

    private void r_InActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_InActiveActionPerformed
        // TODO add your handling code here:
        this.empStatus = false;
        r_Active.setSelected(false);
    }//GEN-LAST:event_r_InActiveActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        this.empGender = "Male";
        r_female.setSelected(false);
        r_otherGender.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        this.empGender = "Female";
        r_male.setSelected(false);
        r_otherGender.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void r_otherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_otherGenderActionPerformed
        // TODO add your handling code here:
        this.empGender = "Other";
        r_female.setSelected(false);
        r_male.setSelected(false);
    }//GEN-LAST:event_r_otherGenderActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg", "gif");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            this.imagePath = selectedImagePath;
            // display image on label
            ImageIcon ii = new ImageIcon(selectedImagePath);
            lblEmployeePic.setIcon(ii);
        }

    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void txtSearch1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearch1FocusGained
        // TODO add your handling code here:
        txtSearch1.setText("");
    }//GEN-LAST:event_txtSearch1FocusGained

    private void txtSearch1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearch1FocusLost
        // TODO add your handling code here:
        if(txtSearch1.getText().isEmpty()) {
            txtSearch1.setText("                                                           Enter Employee Id, First Name or Email to Search");
        }

    }//GEN-LAST:event_txtSearch1FocusLost

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
        String searchTxt = txtSearch1.getText();
        if(txtSearch1.getText().isEmpty()) {
            txtSearch1.setText("                                                           Enter Employee Id, First Name or Email to Search");
        } else {
            populateEmployeesDataToTable(searchTxt);
        }
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtSearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1KeyPressed

    private void updateEmployeePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeePanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmployeePanel1MouseClicked

    private void deleteEmployeePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeePanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeePanel1MouseClicked

    private void addEmployeePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeePanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeePanel1MouseClicked

    private void addEmployeePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeePanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeePanel2MouseClicked

    private void updateEmployeePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeePanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmployeePanel2MouseClicked

    private void deleteEmployeePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeePanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeePanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysAdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysAdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysAdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysAdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysAdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TotalEmpPane;
    private javax.swing.JPanel activeEmpPane;
    private javax.swing.JPanel addEmpPaneHeader;
    private javax.swing.JPanel addEmployeePane;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JPanel addEmployeePanel1;
    private javax.swing.JPanel addEmployeePanel2;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnEmployee;
    private javax.swing.JPanel btnViewLoggedInUserProfile;
    private javax.swing.JPanel btnViewLogout;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel deleteEmployeePanel;
    private javax.swing.JPanel deleteEmployeePanel1;
    private javax.swing.JPanel deleteEmployeePanel2;
    private com.toedter.calendar.JDateChooser empStartDateField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAboutUS;
    private javax.swing.JLabel lblActiveEmp;
    private javax.swing.JLabel lblAddEmployee;
    private javax.swing.JLabel lblAddEmployee1;
    private javax.swing.JLabel lblAddEmployee2;
    private javax.swing.JLabel lblAddEmployeePane;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCloseWindowIcon;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblDashIcon;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDeleteEmployee;
    private javax.swing.JLabel lblDeleteEmployee2;
    private javax.swing.JLabel lblDeleteEmployee3;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDesg;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpIcon;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblEmpInfoIcon;
    private javax.swing.JLabel lblEmpSec;
    private javax.swing.JLabel lblEmpSec1;
    private javax.swing.JLabel lblEmpSec2;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblEmployeePic;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIconAddEmployee;
    private javax.swing.JLabel lblIconAddEmployee1;
    private javax.swing.JLabel lblIconAddEmployee2;
    private javax.swing.JLabel lblIconDeleteEmployee;
    private javax.swing.JLabel lblIconDeleteEmployee1;
    private javax.swing.JLabel lblIconDeleteEmployee2;
    private javax.swing.JLabel lblIconUpdateEmployee;
    private javax.swing.JLabel lblIconUpdateEmployee1;
    private javax.swing.JLabel lblIconUpdateEmployee2;
    private javax.swing.JLabel lblInActiveEmp;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLogoutBtn;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotalEmp;
    private javax.swing.JLabel lblUpdateEmployee;
    private javax.swing.JLabel lblUpdateEmployee1;
    private javax.swing.JLabel lblUpdateEmployee2;
    private javax.swing.JLabel lblUserImg;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblViewUserProfile;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelEmployeeHeader;
    private javax.swing.JPanel panelEmployees;
    private javax.swing.JRadioButton r_Active;
    private javax.swing.JRadioButton r_InActive;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JRadioButton r_otherGender;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblEmployeesData;
    private javax.swing.JLabel txtActiveEmp;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtFname;
    private javax.swing.JLabel txtInactiveEmp;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JLabel txtTotalEmp;
    private javax.swing.JPanel updateEmployeePanel;
    private javax.swing.JPanel updateEmployeePanel1;
    private javax.swing.JPanel updateEmployeePanel2;
    // End of variables declaration//GEN-END:variables
}
