/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import email.RegistrationEmail;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Address;
import models.Person;
import resources.Validations;

/**
 *
 * @author nikhilbindal
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form SignupForm
     */
    private String personType;
    private Validations validate = new Validations();
    Person person = new Person();
    public SignupForm() {
        initComponents();
        ngoSignupForm.setVisible(false);
        vendorSignupForm.setVisible(false);
        userSignupForm.setVisible(true);
        
    }
    
    public SignupForm(String usertype) {
        this.personType = usertype;
        initComponents();
        Address address = new Address();
        ResultSet rs = address.getCityList();
        switch (usertype) {
            case "User":
                ngoSignupForm.setVisible(false);
                vendorSignupForm.setVisible(false);
                userSignupForm.setVisible(true);
                try {
                    while(rs.next()) {
                        comboUserCity.addItem(rs.getString("cityName"));
                    }
                } catch(Exception e) {
                    e.printStackTrace();
                }
                break;
            case "NGO":
                ngoSignupForm.setVisible(true);
                vendorSignupForm.setVisible(false);
                userSignupForm.setVisible(false);
                try {
                    while(rs.next()) {
                        comboNgoCity.addItem(rs.getString("cityName"));
                    }
                } catch(Exception e) {
                    e.printStackTrace();
                }
                break;
            case "Delivery Partner":
                ngoSignupForm.setVisible(false);
                vendorSignupForm.setVisible(true);
                userSignupForm.setVisible(false);
                try {
                    while(rs.next()) {
                        comboVendorCity.addItem(rs.getString("cityName"));
                    }
                } catch(Exception e) {
                    e.printStackTrace();
                }
                break;
            case "Vendor":
                ngoSignupForm.setVisible(false);
                vendorSignupForm.setVisible(true);
                userSignupForm.setVisible(false);
                try {
                    while(rs.next()) {
                        comboVendorCity.addItem(rs.getString("cityName"));
                    }
                } catch(Exception e) {
                    e.printStackTrace();
                }
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSignupForm = new javax.swing.JPanel();
        addEmpPaneHeader = new javax.swing.JPanel();
        lblAddEmployeePane = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        txtUserAge = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtUserSSN = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblDesg = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAddress3 = new javax.swing.JLabel();
        lblEmpId3 = new javax.swing.JLabel();
        lblAddress4 = new javax.swing.JLabel();
        txtUserZip = new javax.swing.JTextField();
        lblAddress5 = new javax.swing.JLabel();
        txtUserState = new javax.swing.JTextField();
        comboUserCity = new javax.swing.JComboBox<>();
        ngoSignupForm = new javax.swing.JPanel();
        addEmpPaneHeader3 = new javax.swing.JPanel();
        lblAddEmployeePane3 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        lblFName3 = new javax.swing.JLabel();
        txtNgoSize = new javax.swing.JTextField();
        lblLName3 = new javax.swing.JLabel();
        txtNgoEmail = new javax.swing.JTextField();
        lblDepartment3 = new javax.swing.JLabel();
        txtNgoUsername = new javax.swing.JTextField();
        lblDesg3 = new javax.swing.JLabel();
        txtNgoPassword = new javax.swing.JTextField();
        lblContactNo3 = new javax.swing.JLabel();
        txtNgoPhone = new javax.swing.JTextField();
        lblAddress6 = new javax.swing.JLabel();
        txtNgoAddress = new javax.swing.JTextField();
        txtNgoName = new javax.swing.JTextField();
        btnAddNgo = new javax.swing.JButton();
        lblEmail3 = new javax.swing.JLabel();
        txtNgoDesc = new javax.swing.JTextField();
        lblAddress7 = new javax.swing.JLabel();
        lblEmpId5 = new javax.swing.JLabel();
        lblAddress8 = new javax.swing.JLabel();
        txtNgoZip = new javax.swing.JTextField();
        lblAddress9 = new javax.swing.JLabel();
        txtNgoState = new javax.swing.JTextField();
        txtNgoManName = new javax.swing.JTextField();
        lblLName4 = new javax.swing.JLabel();
        comboNgoCity = new javax.swing.JComboBox<>();
        vendorSignupForm = new javax.swing.JPanel();
        addEmpPaneHeader5 = new javax.swing.JPanel();
        lblAddEmployeePane5 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        lblFName5 = new javax.swing.JLabel();
        txtVendorContact = new javax.swing.JTextField();
        lblLName5 = new javax.swing.JLabel();
        txtVendorEmail = new javax.swing.JTextField();
        lblDepartment5 = new javax.swing.JLabel();
        txtVendorUsername = new javax.swing.JTextField();
        lblDesg5 = new javax.swing.JLabel();
        txtVendorPassword = new javax.swing.JTextField();
        lblAddress14 = new javax.swing.JLabel();
        txtVendorAddress = new javax.swing.JTextField();
        txtVendorName = new javax.swing.JTextField();
        btnAdd10 = new javax.swing.JButton();
        lblAddress15 = new javax.swing.JLabel();
        lblEmpId9 = new javax.swing.JLabel();
        lblAddress16 = new javax.swing.JLabel();
        txtVendorZip = new javax.swing.JTextField();
        lblAddress17 = new javax.swing.JLabel();
        txtVendorState = new javax.swing.JTextField();
        comboVendorCity = new javax.swing.JComboBox<>();
        lblLName6 = new javax.swing.JLabel();
        txtVendorManName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        userSignupForm.setBackground(new java.awt.Color(218, 228, 230));
        userSignupForm.setPreferredSize(new java.awt.Dimension(769, 560));

        addEmpPaneHeader.setBackground(new java.awt.Color(0, 0, 102));
        addEmpPaneHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addEmpPaneHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEmployeePane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddEmployeePane.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmployeePane.setText("Fill up the following form :");
        addEmpPaneHeader.add(lblAddEmployeePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Go Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        addEmpPaneHeader.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 110, 20));

        lblFName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFName.setForeground(new java.awt.Color(153, 153, 153));
        lblFName.setText("Age:");

        txtUserAge.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUserAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName.setForeground(new java.awt.Color(153, 153, 153));
        lblLName.setText("SSN:");

        txtUserSSN.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUserSSN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDepartment.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(153, 153, 153));
        lblDepartment.setText("Username:");

        txtUsername.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDesg.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDesg.setForeground(new java.awt.Color(153, 153, 153));
        lblDesg.setText("Password:");

        txtPassword.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblContactNo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(153, 153, 153));
        lblContactNo.setText("Contact No :");

        txtNumber.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress.setText("Address :");

        txtAddress.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        txtUserName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        btnAdd.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Sign Up!");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(153, 153, 153));
        lblEmail.setText("Email :");

        txtEmail.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblAddress3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress3.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress3.setText("City:");

        lblEmpId3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmpId3.setForeground(new java.awt.Color(153, 153, 153));
        lblEmpId3.setText("Name:");

        lblAddress4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress4.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress4.setText("Zipcode :");

        txtUserZip.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUserZip.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress5.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress5.setText("State :");

        txtUserState.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtUserState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout userSignupFormLayout = new javax.swing.GroupLayout(userSignupForm);
        userSignupForm.setLayout(userSignupFormLayout);
        userSignupFormLayout.setHorizontalGroup(
            userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(userSignupFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress5)
                            .addComponent(txtUserState, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress4)
                            .addComponent(txtUserZip, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSignupFormLayout.createSequentialGroup()
                        .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(userSignupFormLayout.createSequentialGroup()
                                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addComponent(lblFName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUserAge, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDepartment, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblEmpId3))
                                .addGap(18, 18, 18)
                                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDesg)
                                    .addComponent(lblLName)
                                    .addComponent(txtPassword)
                                    .addComponent(txtUserSSN)
                                    .addComponent(lblContactNo)
                                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userSignupFormLayout.createSequentialGroup()
                                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress3)
                                    .addComponent(comboUserCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSignupFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        userSignupFormLayout.setVerticalGroup(
            userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSignupFormLayout.createSequentialGroup()
                .addComponent(addEmpPaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblEmpId3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblContactNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblFName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblLName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(lblDesg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblAddress3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboUserCity)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(userSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblAddress5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userSignupFormLayout.createSequentialGroup()
                        .addComponent(lblAddress4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserZip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        ngoSignupForm.setBackground(new java.awt.Color(218, 228, 230));
        ngoSignupForm.setPreferredSize(new java.awt.Dimension(769, 560));

        addEmpPaneHeader3.setBackground(new java.awt.Color(0, 0, 102));
        addEmpPaneHeader3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addEmpPaneHeader3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEmployeePane3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddEmployeePane3.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmployeePane3.setText("Fill up the following form :");
        addEmpPaneHeader3.add(lblAddEmployeePane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        btnBack3.setBackground(new java.awt.Color(255, 0, 51));
        btnBack3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnBack3.setText("Go Back");
        btnBack3.setBorderPainted(false);
        btnBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack3MouseClicked(evt);
            }
        });
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        addEmpPaneHeader3.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 100, 20));

        lblFName3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFName3.setForeground(new java.awt.Color(153, 153, 153));
        lblFName3.setText("Size:");

        txtNgoSize.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoSize.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName3.setForeground(new java.awt.Color(153, 153, 153));
        lblLName3.setText("Email:");

        txtNgoEmail.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDepartment3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment3.setForeground(new java.awt.Color(153, 153, 153));
        lblDepartment3.setText("Username:");

        txtNgoUsername.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDesg3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDesg3.setForeground(new java.awt.Color(153, 153, 153));
        lblDesg3.setText("Password:");

        txtNgoPassword.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblContactNo3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblContactNo3.setForeground(new java.awt.Color(153, 153, 153));
        lblContactNo3.setText("Contact No :");

        txtNgoPhone.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress6.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress6.setText("Address :");

        txtNgoAddress.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        txtNgoName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        btnAddNgo.setBackground(new java.awt.Color(0, 0, 102));
        btnAddNgo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAddNgo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNgo.setText("Sign Up!");
        btnAddNgo.setBorderPainted(false);
        btnAddNgo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNgoActionPerformed(evt);
            }
        });

        lblEmail3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(153, 153, 153));
        lblEmail3.setText("Description:");

        txtNgoDesc.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoDesc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtNgoDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgoDescActionPerformed(evt);
            }
        });

        lblAddress7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress7.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress7.setText("City:");

        lblEmpId5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmpId5.setForeground(new java.awt.Color(153, 153, 153));
        lblEmpId5.setText("Organisation Name:");

        lblAddress8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress8.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress8.setText("Zipcode :");

        txtNgoZip.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoZip.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress9.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress9.setText("State :");

        txtNgoState.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        txtNgoManName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtNgoManName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName4.setForeground(new java.awt.Color(153, 153, 153));
        lblLName4.setText("Manager's Name:");

        javax.swing.GroupLayout ngoSignupFormLayout = new javax.swing.GroupLayout(ngoSignupForm);
        ngoSignupForm.setLayout(ngoSignupFormLayout);
        ngoSignupFormLayout.setHorizontalGroup(
            ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ngoSignupFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ngoSignupFormLayout.createSequentialGroup()
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNgoName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFName3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgoSize, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDepartment3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblContactNo3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgoUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgoPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblEmpId5))
                                .addGap(18, 18, 18)
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDesg3)
                                    .addComponent(lblLName3)
                                    .addComponent(txtNgoPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtNgoEmail)
                                    .addComponent(lblLName4)
                                    .addComponent(txtNgoManName)))
                            .addComponent(lblEmail3)
                            .addComponent(txtNgoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ngoSignupFormLayout.createSequentialGroup()
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress6)
                                    .addComponent(txtNgoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress7)
                                    .addComponent(comboNgoCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ngoSignupFormLayout.createSequentialGroup()
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress9)
                                    .addComponent(txtNgoState, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress8)
                                    .addComponent(txtNgoZip, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(368, 368, 368))
                    .addComponent(btnAddNgo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        ngoSignupFormLayout.setVerticalGroup(
            ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ngoSignupFormLayout.createSequentialGroup()
                .addComponent(addEmpPaneHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblEmpId5)
                        .addGap(13, 13, 13)
                        .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgoName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgoManName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLName4))
                .addGap(18, 18, 18)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblFName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgoSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblLName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment3)
                    .addComponent(lblDesg3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContactNo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblEmail3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(txtNgoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAddress6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboNgoCity)))
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblAddress7)
                        .addGap(42, 42, 42)))
                .addGap(18, 18, 18)
                .addGroup(ngoSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblAddress9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgoState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ngoSignupFormLayout.createSequentialGroup()
                        .addComponent(lblAddress8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgoZip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNgo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        vendorSignupForm.setBackground(new java.awt.Color(218, 228, 230));
        vendorSignupForm.setPreferredSize(new java.awt.Dimension(769, 560));

        addEmpPaneHeader5.setBackground(new java.awt.Color(0, 0, 102));
        addEmpPaneHeader5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addEmpPaneHeader5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEmployeePane5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddEmployeePane5.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmployeePane5.setText("Fill up the following form :");
        addEmpPaneHeader5.add(lblAddEmployeePane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, -1, -1));

        btnBack5.setBackground(new java.awt.Color(255, 0, 51));
        btnBack5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack5.setForeground(new java.awt.Color(255, 255, 255));
        btnBack5.setText("Go Back");
        btnBack5.setBorderPainted(false);
        btnBack5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack5MouseClicked(evt);
            }
        });
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });
        addEmpPaneHeader5.add(btnBack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 20));

        lblFName5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFName5.setForeground(new java.awt.Color(153, 153, 153));
        lblFName5.setText("Contact:");

        txtVendorContact.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName5.setForeground(new java.awt.Color(153, 153, 153));
        lblLName5.setText("Email:");

        txtVendorEmail.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDepartment5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment5.setForeground(new java.awt.Color(153, 153, 153));
        lblDepartment5.setText("Username:");

        txtVendorUsername.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblDesg5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDesg5.setForeground(new java.awt.Color(153, 153, 153));
        lblDesg5.setText("Password:");

        txtVendorPassword.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress14.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress14.setText("Address :");

        txtVendorAddress.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        txtVendorName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        btnAdd10.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAdd10.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd10.setText("Sign Up!");
        btnAdd10.setBorderPainted(false);
        btnAdd10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd10ActionPerformed(evt);
            }
        });

        lblAddress15.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress15.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress15.setText("City:");

        lblEmpId9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmpId9.setForeground(new java.awt.Color(153, 153, 153));
        lblEmpId9.setText("Organisation Name:");

        lblAddress16.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress16.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress16.setText("Zipcode :");

        txtVendorZip.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorZip.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAddress17.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAddress17.setForeground(new java.awt.Color(153, 153, 153));
        lblAddress17.setText("State :");

        txtVendorState.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblLName6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName6.setForeground(new java.awt.Color(153, 153, 153));
        lblLName6.setText("Manager's Name:");

        txtVendorManName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        txtVendorManName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout vendorSignupFormLayout = new javax.swing.GroupLayout(vendorSignupForm);
        vendorSignupForm.setLayout(vendorSignupFormLayout);
        vendorSignupFormLayout.setHorizontalGroup(
            vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPaneHeader5, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vendorSignupFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress17)
                            .addComponent(txtVendorState, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress16)
                            .addComponent(txtVendorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress14)
                            .addComponent(txtVendorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress15)
                            .addComponent(comboVendorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtVendorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(lblFName5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVendorContact, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDepartment5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVendorUsername, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblEmpId9))
                        .addGap(18, 18, 18)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLName6)
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtVendorManName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDesg5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLName5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVendorPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtVendorEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        vendorSignupFormLayout.setVerticalGroup(
            vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                .addComponent(addEmpPaneHeader5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                        .addComponent(lblEmpId9)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                        .addComponent(lblLName6)
                                        .addGap(43, 43, 43))))
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(txtVendorManName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblFName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVendorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblLName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDepartment5)
                            .addComponent(lblDesg5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVendorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVendorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblAddress14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVendorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboVendorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblAddress15)
                                .addGap(42, 42, 42)))
                        .addGroup(vendorSignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblAddress17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVendorState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vendorSignupFormLayout.createSequentialGroup()
                                .addComponent(lblAddress16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVendorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(226, Short.MAX_VALUE))
                    .addGroup(vendorSignupFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ngoSignupForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(userSignupForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vendorSignupForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ngoSignupForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(userSignupForm, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vendorSignupForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnAddNgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNgoActionPerformed
        // TODO add your handling code here:
        
        // User Details
        String name = txtNgoManName.getText();
        String email = txtNgoEmail.getText();
        String phnNo = txtNgoPhone.getText();
        String uname = txtNgoUsername.getText();
        String pass = txtNgoPassword.getText();
        String orgName = txtNgoName.getText();
        String ngoDesc = txtNgoDesc.getText();
        int ngoSize = txtNgoSize.getText().equals("") ? 0 : Integer.parseInt(txtNgoSize.getText());
        
        // Adddress Details
        String street = txtNgoAddress.getText();
        String city = comboNgoCity.getSelectedItem().toString();
        String state = txtNgoState.getText();
        String zip = txtNgoZip.getText();
        // Validate User first
        if(!validate.ValidateEmpty(name)) {
            JOptionPane.showMessageDialog(this, "Please enter the Manager's name");
        } else if(!validate.ValidateEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid email");
        } else if(person.checkIfEmailExists(email)) {
            JOptionPane.showMessageDialog(this, "Email already exists");
        } else if(!validate.ValidatePhoneNumber(phnNo)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid phone number");
        } else if(person.checkIfPhoneNoExists(phnNo)) {
            JOptionPane.showMessageDialog(this, "Phone number already exists");
        } else if(!validate.ValidateUsername(uname)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid username");
        } else if(person.checkIfUsernameExists(uname)) {
            JOptionPane.showMessageDialog(this, "Username already exists");
        } else if(!validate.ValidatePassword(pass)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid password between 5-12 characters");
        } else if(!validate.ValidateEmpty(orgName)) {
            JOptionPane.showMessageDialog(this, "Please enter the organisation name");
        } else if(!validate.ValidateEmpty(ngoDesc)) {
            JOptionPane.showMessageDialog(this, "Please enter the description");
        } else if(ngoSize == 0) {
            JOptionPane.showMessageDialog(this, "Please enter the NGO size");
        } else if(!validate.ValidateEmpty(street)) {
            JOptionPane.showMessageDialog(this, "Please enter the Address");
        } else if(!validate.ValidateEmpty(city)) {
            JOptionPane.showMessageDialog(this, "Please select the city");
        } else if(!validate.ValidateEmpty(state)) {
            JOptionPane.showMessageDialog(this, "Please enter the state");
        } else if(!validate.ValidateEmpty(zip)) {
            JOptionPane.showMessageDialog(this, "Please enter the zip code");
        } else {
            // Create address first
            Address address = new Address();
            int addressId = address.createAddress(street, city, state, zip);

            Person person = new Person();
            person.createNgo(name, email, phnNo, uname, pass, ngoSize, orgName, addressId, ngoDesc, city);
            String email1 = "vicken.test@gmail.com";
            try {
                RegistrationEmail.registration(email); 
            } catch (Exception ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ConfirmationModel confirm = new ConfirmationModel();
            confirm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAddNgoActionPerformed

    private void txtNgoDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgoDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgoDescActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnAdd10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd10ActionPerformed
        // TODO add your handling code here:
        String street = txtVendorAddress.getText();
        String city = comboVendorCity.getSelectedItem().toString();
        String state = txtVendorState.getText();
        String zip = txtVendorZip.getText();
        
        String name = txtVendorManName.getText();
        String email = txtVendorEmail.getText();
        String phnNo = txtVendorContact.getText();
        String uname = txtVendorUsername.getText();
        String pass = txtVendorPassword.getText();
        String orgName = txtVendorName.getText();
        if(!validate.ValidateEmpty(name)) {
            JOptionPane.showMessageDialog(this, "Please enter the Manager's name");
        } else if(!validate.ValidateEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid email");
        } else if(person.checkIfEmailExists(email)) {
            JOptionPane.showMessageDialog(this, "Email already exists");
        } else if(!validate.ValidatePhoneNumber(phnNo)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid phone number");
        } else if(person.checkIfPhoneNoExists(phnNo)) {
            JOptionPane.showMessageDialog(this, "Phone number already exists");
        } else if(!validate.ValidateUsername(uname)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid username");
        } else if(person.checkIfUsernameExists(uname)) {
            JOptionPane.showMessageDialog(this, "Username already exists");
        } else if(!validate.ValidatePassword(pass)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid password between 5-12 characters");
        } else if(!validate.ValidateEmpty(orgName)) {
            JOptionPane.showMessageDialog(this, "Please enter the organisation name");
        } else if(!validate.ValidateEmpty(street)) {
            JOptionPane.showMessageDialog(this, "Please enter the Address");
        } else if(!validate.ValidateEmpty(city)) {
            JOptionPane.showMessageDialog(this, "Please select the city");
        } else if(!validate.ValidateEmpty(state)) {
            JOptionPane.showMessageDialog(this, "Please enter the state");
        } else if(!validate.ValidateEmpty(zip)) {
            JOptionPane.showMessageDialog(this, "Please enter the zip code");
        } else {
            Address address = new Address();
            int addressId = address.createAddress(street, city, state, zip);
            Person person = new Person();
            
            if(personType == "Vendor") {
                person.createVendor(name, email, phnNo, uname, pass, orgName, addressId, city);
            } else {
                person.createDelivery(name, email, phnNo, uname, pass, orgName, addressId, city);
            }
            String email1 = "vicken.test@gmail.com";
            try {
                RegistrationEmail.registration(email); 
            } catch (Exception ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ConfirmationModel confirm = new ConfirmationModel();
            confirm.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnAdd10ActionPerformed

    private void btnBack5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack5MouseClicked

    private void btnBack3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack3MouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack3MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        
        // Create address first
        Address address = new Address();
        String street = txtAddress.getText();
        String city = comboUserCity.getSelectedItem().toString();
        String state = txtUserState.getText();
        String zip = txtUserZip.getText();
        
        Person person = new Person();
        String name = txtUserName.getText();
        String email = txtEmail.getText();
        String phnNo = txtNumber.getText();
        String uname = txtUsername.getText();
        String pass = txtPassword.getText();
        int age = Integer.parseInt(txtUserAge.getText());
        String ssn = txtUserSSN.getText();
        
        if(!validate.ValidateEmpty(name)) {
            JOptionPane.showMessageDialog(this, "Please enter the Manager's name");
        } else if(!validate.ValidateEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid email");
        } else if(person.checkIfEmailExists(email)) {
            JOptionPane.showMessageDialog(this, "Email already exists");
        } else if(!validate.ValidatePhoneNumber(phnNo)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid phone number");
        } else if(person.checkIfPhoneNoExists(phnNo)) {
            JOptionPane.showMessageDialog(this, "Phone number already exists");
        } else if(!validate.ValidateUsername(uname)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid username");
        } else if(person.checkIfUsernameExists(uname)) {
            JOptionPane.showMessageDialog(this, "Username already exists");
        } else if(!validate.ValidatePassword(pass)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid password between 5-12 characters");
        } else if(!validate.ValidateSSN(ssn)) {
            JOptionPane.showMessageDialog(this, "Please enter the valid SSN");
        } else if(person.checkIfSSNExists(ssn)) {
            JOptionPane.showMessageDialog(this, "SSN already exists");
        } else if(!validate.ValidateEmpty(street)) {
            JOptionPane.showMessageDialog(this, "Please enter the Address");
        } else if(!validate.ValidateEmpty(city)) {
            JOptionPane.showMessageDialog(this, "Please select the city");
        } else if(!validate.ValidateEmpty(state)) {
            JOptionPane.showMessageDialog(this, "Please enter the state");
        } else if(!validate.ValidateEmpty(zip)) {
            JOptionPane.showMessageDialog(this, "Please enter the zip code");
        } else {
            int addressId = address.createAddress(street, city, state, zip);
            person.createPerson(name, email, phnNo, uname, pass, age, ssn, addressId);
            String email1 = "vicken.test@gmail.com";
            try {
                RegistrationEmail.registration(email); 
            } catch (Exception ex) {
                Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ConfirmationModel confirm = new ConfirmationModel();
            confirm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addEmpPaneHeader;
    private javax.swing.JPanel addEmpPaneHeader3;
    private javax.swing.JPanel addEmpPaneHeader5;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd10;
    private javax.swing.JButton btnAddNgo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack5;
    private javax.swing.JComboBox<String> comboNgoCity;
    private javax.swing.JComboBox<String> comboUserCity;
    private javax.swing.JComboBox<String> comboVendorCity;
    private javax.swing.JLabel lblAddEmployeePane;
    private javax.swing.JLabel lblAddEmployeePane3;
    private javax.swing.JLabel lblAddEmployeePane5;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress14;
    private javax.swing.JLabel lblAddress15;
    private javax.swing.JLabel lblAddress16;
    private javax.swing.JLabel lblAddress17;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblAddress5;
    private javax.swing.JLabel lblAddress6;
    private javax.swing.JLabel lblAddress7;
    private javax.swing.JLabel lblAddress8;
    private javax.swing.JLabel lblAddress9;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactNo3;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartment3;
    private javax.swing.JLabel lblDepartment5;
    private javax.swing.JLabel lblDesg;
    private javax.swing.JLabel lblDesg3;
    private javax.swing.JLabel lblDesg5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblEmpId3;
    private javax.swing.JLabel lblEmpId5;
    private javax.swing.JLabel lblEmpId9;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFName3;
    private javax.swing.JLabel lblFName5;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLName3;
    private javax.swing.JLabel lblLName4;
    private javax.swing.JLabel lblLName5;
    private javax.swing.JLabel lblLName6;
    private javax.swing.JPanel ngoSignupForm;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNgoAddress;
    private javax.swing.JTextField txtNgoDesc;
    private javax.swing.JTextField txtNgoEmail;
    private javax.swing.JTextField txtNgoManName;
    private javax.swing.JTextField txtNgoName;
    private javax.swing.JTextField txtNgoPassword;
    private javax.swing.JTextField txtNgoPhone;
    private javax.swing.JTextField txtNgoSize;
    private javax.swing.JTextField txtNgoState;
    private javax.swing.JTextField txtNgoUsername;
    private javax.swing.JTextField txtNgoZip;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserAge;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserSSN;
    private javax.swing.JTextField txtUserState;
    private javax.swing.JTextField txtUserZip;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtVendorAddress;
    private javax.swing.JTextField txtVendorContact;
    private javax.swing.JTextField txtVendorEmail;
    private javax.swing.JTextField txtVendorManName;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JTextField txtVendorPassword;
    private javax.swing.JTextField txtVendorState;
    private javax.swing.JTextField txtVendorUsername;
    private javax.swing.JTextField txtVendorZip;
    private javax.swing.JPanel userSignupForm;
    private javax.swing.JPanel vendorSignupForm;
    // End of variables declaration//GEN-END:variables
}
